from __future__ import annotations

import argparse
import json
import shlex
from dataclasses import dataclass
from pathlib import Path


SCHEMA_VERSION = 1
GROUNDINGDINO_REPO_URL = "https://github.com/IDEA-Research/GroundingDINO.git"
GROUNDINGDINO_CHECKPOINT_URL = "https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth"
SAM3_REPO_URL = "https://github.com/facebookresearch/sam3.git"
DEFAULT_TEXT_PROMPT = "object . foreground object . plane . floor . wall . box . sphere . cylinder . cone . chair . table ."
SMOKE_IMAGE_PATH = "Assets/Fixtures/OpenVocabulary/open_vocab_smoke_objects.png"
SMOKE_PROMPT_PATH = "Assets/Fixtures/OpenVocabulary/open_vocab_smoke_prompt.txt"


@dataclass(frozen=True)
class OpenVocabLayout:
    root_dir: Path

    @property
    def groundingdino_dir(self) -> Path:
        return self.root_dir / "GroundingDINO"

    @property
    def groundingdino_repo_dir(self) -> Path:
        return self.groundingdino_dir / "repo"

    @property
    def groundingdino_weights_dir(self) -> Path:
        return self.groundingdino_dir / "weights"

    @property
    def groundingdino_config(self) -> Path:
        return self.groundingdino_repo_dir / "groundingdino" / "config" / "GroundingDINO_SwinT_OGC.py"

    @property
    def groundingdino_checkpoint(self) -> Path:
        return self.groundingdino_weights_dir / "groundingdino_swint_ogc.pth"

    @property
    def sam3_dir(self) -> Path:
        return self.root_dir / "SAM3"

    @property
    def sam3_repo_dir(self) -> Path:
        return self.sam3_dir / "repo"

    @property
    def sam3_model_dir(self) -> Path:
        return self.sam3_dir / "hf"

    @property
    def setup_script(self) -> Path:
        return self.root_dir / "setup_open_vocab_sources.sh"

    @property
    def manifest_path(self) -> Path:
        return self.root_dir / "open_vocab_setup_manifest.json"


def prepare_layout(root_dir: str | Path, *, create_dirs: bool = True, write_script: bool = True) -> dict:
    layout = OpenVocabLayout(Path(root_dir))
    directories = [
        layout.root_dir,
        layout.groundingdino_dir,
        layout.groundingdino_weights_dir,
        layout.sam3_dir,
        layout.sam3_model_dir,
    ]
    if create_dirs:
        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)
    script_text = build_setup_script(layout)
    if write_script:
        layout.root_dir.mkdir(parents=True, exist_ok=True)
        layout.setup_script.write_text(script_text, encoding="utf-8")
        layout.setup_script.chmod(0o755)
    manifest = build_manifest(layout, script_text=script_text)
    if create_dirs:
        layout.manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def build_manifest(layout: OpenVocabLayout, *, script_text: str) -> dict:
    return {
        "schema_version": SCHEMA_VERSION,
        "root_dir": str(layout.root_dir),
        "sources": {
            "groundingdino_repo_url": GROUNDINGDINO_REPO_URL,
            "groundingdino_checkpoint_url": GROUNDINGDINO_CHECKPOINT_URL,
            "sam3_repo_url": SAM3_REPO_URL,
            "sam3_checkpoint_note": "SAM3 checkpoints require accepted Hugging Face access and authentication; keep HF_HOME/HUGGINGFACE_HUB_CACHE under sam3_model_dir.",
        },
        "paths": {
            "smoke_image_path": SMOKE_IMAGE_PATH,
            "smoke_prompt_path": SMOKE_PROMPT_PATH,
            "groundingdino_repo_dir": str(layout.groundingdino_repo_dir),
            "groundingdino_config": str(layout.groundingdino_config),
            "groundingdino_checkpoint": str(layout.groundingdino_checkpoint),
            "sam3_repo_dir": str(layout.sam3_repo_dir),
            "sam3_model_dir": str(layout.sam3_model_dir),
            "setup_script": str(layout.setup_script),
        },
        "workflow": [
            "Run setup_open_vocab_sources.sh manually when ready to clone/download public assets.",
            "Authenticate to Hugging Face before SAM3 checkpoint access if needed.",
            "Run check-open-vocab-integration.",
            "Run probe-open-vocab-imports.",
            "Run detect-shapes --backend groundingdino-sam3 on the smoke fixture image.",
        ],
        "smoke_test_command": smoke_test_command(layout),
        "preflight_command": preflight_command(layout),
        "import_probe_command": import_probe_command(layout),
        "setup_script_preview": script_text,
    }


def build_setup_script(layout: OpenVocabLayout) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by SceneForge. Review before running; this script performs network operations.",
        "cd " + shlex.quote(str(layout.root_dir)),
        "",
        "mkdir -p GroundingDINO/weights SAM3/hf",
        "SCENEFORGE_ROOT=$(cd ../.. && pwd)",
        'SCENEFORGE_PYTHON=${SCENEFORGE_PYTHON:-$SCENEFORGE_ROOT/.venv/bin/python}',
        'if [ ! -x "$SCENEFORGE_PYTHON" ]; then',
        '  python3 -m venv "$SCENEFORGE_ROOT/.venv"',
        '  SCENEFORGE_PYTHON="$SCENEFORGE_ROOT/.venv/bin/python"',
        "fi",
        '"$SCENEFORGE_PYTHON" -m pip install --upgrade pip',
        '"$SCENEFORGE_PYTHON" -m pip install -r "$SCENEFORGE_ROOT/requirements.txt"',
        '"$SCENEFORGE_PYTHON" -m pip install nvidia-cuda-nvcc',
        'CUDA_HOME=$("$SCENEFORGE_PYTHON" - <<\'PY\'',
        "from pathlib import Path",
        "import site",
        "",
        "for base in site.getsitepackages():",
        "    for nvcc in sorted(Path(base).glob('nvidia/cu*/bin/nvcc')):",
        "        print(nvcc.parents[1])",
        "        raise SystemExit(0)",
        "raise SystemExit('nvidia-cuda-nvcc installed, but nvcc was not found')",
        "PY",
        ")",
        'export CUDA_HOME',
        'export PATH="$CUDA_HOME/bin:$PATH"',
        'if [ -f "$CUDA_HOME/lib/libcudart.so.13" ] && [ ! -e "$CUDA_HOME/lib/libcudart.so" ]; then',
        '  ln -s libcudart.so.13 "$CUDA_HOME/lib/libcudart.so"',
        "fi",
        'export LIBRARY_PATH="$CUDA_HOME/lib:${LIBRARY_PATH:-}"',
        'export LD_LIBRARY_PATH="$CUDA_HOME/lib:${LD_LIBRARY_PATH:-}"',
        "",
        "if [ ! -d GroundingDINO/repo/.git ]; then",
        f"  git clone {shlex.quote(GROUNDINGDINO_REPO_URL)} GroundingDINO/repo",
        "fi",
        '"$SCENEFORGE_PYTHON" - <<\'PY\'',
        "from pathlib import Path",
        "",
        "source = Path('GroundingDINO/repo/groundingdino/models/GroundingDINO/csrc/MsDeformAttn/ms_deform_attn_cuda.cu')",
        "text = source.read_text(encoding='utf-8')",
        "text = text.replace(",
        "    'AT_DISPATCH_FLOATING_TYPES(value.type(), \"ms_deform_attn_forward_cuda\",',",
        "    'AT_DISPATCH_FLOATING_TYPES(value.scalar_type(), \"ms_deform_attn_forward_cuda\",',",
        ")",
        "text = text.replace(",
        "    'AT_DISPATCH_FLOATING_TYPES(value.type(), \"ms_deform_attn_backward_cuda\",',",
        "    'AT_DISPATCH_FLOATING_TYPES(value.scalar_type(), \"ms_deform_attn_backward_cuda\",',",
        ")",
        "text = text.replace('value.scalar_type().is_cuda()', 'value.is_cuda()')",
        "source.write_text(text, encoding='utf-8')",
        "PY",
        '"$SCENEFORGE_PYTHON" -m pip install --no-build-isolation -e GroundingDINO/repo',
        "if [ ! -f GroundingDINO/weights/groundingdino_swint_ogc.pth ]; then",
        f"  wget -O GroundingDINO/weights/groundingdino_swint_ogc.pth {shlex.quote(GROUNDINGDINO_CHECKPOINT_URL)}",
        "fi",
        "",
        "if [ ! -d SAM3/repo/.git ]; then",
        f"  git clone {shlex.quote(SAM3_REPO_URL)} SAM3/repo",
        "fi",
        '"$SCENEFORGE_PYTHON" -m pip install --no-build-isolation -e SAM3/repo',
        "",
        "# SAM3 checkpoints are access-gated. After approval, authenticate with:",
        "#   hf auth login",
        "# The SceneForge adapter sets HF_HOME/HUGGINGFACE_HUB_CACHE to SAM3/hf at runtime.",
        "",
        'cd "$SCENEFORGE_ROOT"',
        '"$SCENEFORGE_PYTHON" run.py check-open-vocab-integration --backend groundingdino-sam3',
        '"$SCENEFORGE_PYTHON" run.py probe-open-vocab-imports --backend groundingdino-sam3',
        "",
    ]
    return "\n".join(lines)


def preflight_command(layout: OpenVocabLayout) -> list[str]:
    return [
        "python3",
        "run.py",
        "check-open-vocab-integration",
        "--backend",
        "groundingdino-sam3",
        "--groundingdino-repo-dir",
        str(layout.groundingdino_repo_dir),
        "--groundingdino-config",
        str(layout.groundingdino_config),
        "--groundingdino-checkpoint",
        str(layout.groundingdino_checkpoint),
        "--sam3-repo-dir",
        str(layout.sam3_repo_dir),
        "--sam3-model-dir",
        str(layout.sam3_model_dir),
        "--output",
        "Output/Latest/open_vocab_preflight.json",
    ]


def import_probe_command(layout: OpenVocabLayout) -> list[str]:
    return [
        "python3",
        "run.py",
        "probe-open-vocab-imports",
        "--backend",
        "groundingdino-sam3",
        "--groundingdino-repo-dir",
        str(layout.groundingdino_repo_dir),
        "--sam3-repo-dir",
        str(layout.sam3_repo_dir),
        "--output",
        "Output/Latest/open_vocab_import_probe.json",
    ]


def smoke_test_command(layout: OpenVocabLayout) -> list[str]:
    return [
        "python3",
        "run.py",
        "detect-shapes",
        "--backend",
        "groundingdino-sam3",
        "--image",
        SMOKE_IMAGE_PATH,
        "--groundingdino-repo-dir",
        str(layout.groundingdino_repo_dir),
        "--groundingdino-config",
        str(layout.groundingdino_config),
        "--groundingdino-checkpoint",
        str(layout.groundingdino_checkpoint),
        "--sam3-repo-dir",
        str(layout.sam3_repo_dir),
        "--sam3-model-dir",
        str(layout.sam3_model_dir),
        "--text-prompt",
        DEFAULT_TEXT_PROMPT,
        "--output",
        "Output/Latest/detect",
        "--device",
        "auto",
    ]


def shell_join(parts: list[str]) -> str:
    return " ".join(shlex.quote(str(part)) for part in parts)


def print_summary(manifest: dict) -> None:
    print(f"prepared open-vocab layout: {manifest['root_dir']}")
    print(f"manifest: {Path(manifest['root_dir']) / 'open_vocab_setup_manifest.json'}")
    print(f"setup script: {manifest['paths']['setup_script']}")
    print("preflight command:")
    print(shell_join(manifest["preflight_command"]))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Prepare local folders and a reviewed setup script for GroundingDINO/SAM3 integration.")
    parser.add_argument("--root", default="Models/OpenVocabulary")
    parser.add_argument("--no-create-dirs", action="store_true")
    parser.add_argument("--no-script", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    manifest = prepare_layout(args.root, create_dirs=not args.no_create_dirs, write_script=not args.no_script)
    print_summary(manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
